spring:
  application:
    name: consumer
  threads:
    virtual:
      enabled: true

server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

producer:
  url: ${PRODUCER_URL}